{"uuid": "80a849c9-1ab7-44d9-bf15-fbb63ae77580", "children": ["72c541ed-bde3-447a-a6d4-5fef04cadc76", "cbbef64e-4bdc-4437-91fd-a37d8a59f702"], "befores": [{"name": "unittest_setUpClass_fixture_TesINDIANBBQKIT", "status": "passed", "start": 1638300468953, "stop": 1638300486707}], "afters": [{"name": "unittest_setUpClass_fixture_TesINDIANBBQKIT::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=38567): Max retries exceeded with url: /session/13eed6403710ee36478792bfc7abe8b8/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1fb41e9910>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/excellence/.local/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"/usr/local/lib/python3.8/dist-packages/_pytest/unittest.py\", line 175, in fixture\n    teardown()\n  File \"/home/excellence/PycharmProjects/gitAutomation/tests/testing_BBQ.py\", line 47, in tearDownClass\n    super(TesINDIANBBQKIT, cls).tearDownClass()\n  File \"/home/excellence/PycharmProjects/gitAutomation/resources/ui_test_class.py\", line 647, in tearDownClass\n    cls.driver.close()\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/usr/lib/python3/dist-packages/urllib3/request.py\", line 75, in request\n    return self.request_encode_url(\n  File \"/usr/lib/python3/dist-packages/urllib3/request.py\", line 97, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/usr/lib/python3/dist-packages/urllib3/poolmanager.py\", line 330, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 747, in urlopen\n    return self.urlopen(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 747, in urlopen\n    return self.urlopen(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 747, in urlopen\n    return self.urlopen(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"/usr/lib/python3/dist-packages/urllib3/util/retry.py\", line 436, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1638300585674, "stop": 1638300585685}], "start": 1638300468953, "stop": 1638300585685}